#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED
#define SIZE 9
#define SUBSQUEARE_SIZE 3

#define EASY_DIF_EMPTY_CELLS    40
#define NORMAL_DIF_EMPTY_CELLS  50
#define HARD_DIF_EMPTY_CELLS    60

#define SAVED_GAMES_DIR "Saved_games"
#define FILENAME_EXTENSION ".sud"

enum DIFFICULTY {EASY = EASY_DIF_EMPTY_CELLS,
                 NORMAL = NORMAL_DIF_EMPTY_CELLS,
                 HARD = HARD_DIF_EMPTY_CELLS};

#endif CONSTANTS_H_INCLUDED
